In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from statsmodels.tsa.ar_model import AutoReg

In [3]:
nifty50 = [
    'ADANIPORTS.NS', 'ASIANPAINT.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS',
    'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BHARTIARTL.NS', 'BPCL.NS',
    'BRITANNIA.NS', 'CIPLA.NS', 'COALINDIA.NS', 'DIVISLAB.NS',
    'DRREDDY.NS', 'EICHERMOT.NS', 'GRASIM.NS', 'HCLTECH.NS',
    'HDFCBANK.NS', 'HEROMOTOCO.NS', 'HINDALCO.NS',
    'HINDUNILVR.NS', 'ICICIBANK.NS', 'INDUSINDBK.NS', 'INFY.NS',
    'ITC.NS', 'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LT.NS',
    'M&M.NS', 'MARUTI.NS', 'NESTLEIND.NS', 'NTPC.NS',
    'ONGC.NS', 'POWERGRID.NS', 'RELIANCE.NS', 'SBILIFE.NS',
    'SBIN.NS', 'SHREECEM.NS', 'SUNPHARMA.NS', 'TATACONSUM.NS',
    'TATAMOTORS.NS', 'TATASTEEL.NS', 'TCS.NS', 'TECHM.NS',
    'TITAN.NS', 'UPL.NS', 'ULTRACEMCO.NS', 'WIPRO.NS',
    'HDFCLIFE.NS', 'ADANIENT.NS'
]
start, end = '2022-01-01','2024-09-01'

In [4]:
data = yf.download(nifty50,start=start,end=end)
data

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  49 of 49 completed

Price             Close                                           \
Ticker      ADANIENT.NS ADANIPORTS.NS ASIANPAINT.NS  AXISBANK.NS
Date
2022-01-03  1713.138062    720.039673   3301.071045   693.329041
2022-01-04  1714.983521    722.630127   3336.662598   706.073608
2022-01-05  1711.441895    737.928345   3401.770020   723.746582
2022-01-06  1709.097290    723.167725   3390.050293   727.131775
2022-01-07  1695.130249    719.550964   3449.514893   727.430481
...                 ...           ...           ...          ...
2024-08-26  3067.431641   1475.372070   3136.981201  1170.300049
2024-08-27  3065.532715   1471.192383   3131.886719  1181.250000
2024-08-28  3026.452637   1462.683838   3091.627686  1170.949951
2024-08-29  3018.606445   1468.903564   3082.082520  1175.400024
2024-08-30  3017.807129   1474.725220   3092.913818  1175.250000

Price                                                               \
Ticker     BAJAJ-AUTO.NS BAJAJFINSV.NS BAJFINANCE.NS BHARTIARTL.NS
Date
2022-01-03   3040.009521   1695.554688   7083.483398    681.297241
2022-01-04   3051.187500   1710.946411   7204.556152    687.358276
2022-01-05   3115.566650   1796.111938   7526.175781    689.871277
2022-01-06   3170.901367   1795.922363   7602.166016    700.120850
2022-01-07   3147.060303   1772.997070   7514.941895    694.503357
...                  ...           ...           ...           ...
2024-08-26  10432.549805   1686.199951   6736.780762   1513.550049
2024-08-27  10501.599609   1719.000000   6821.507812   1522.750000
2024-08-28  10656.750000   1713.500000   6857.684570   1556.349976
2024-08-29  10807.849609   1755.650024   7020.231445   1565.900024
2024-08-30  10891.549805   1783.050049   7155.994141   1589.050049

Price                                ...       Volume                \
Ticker         BPCL.NS BRITANNIA.NS  ... SUNPHARMA.NS TATACONSUM.NS
Date                                 ...
2022-01-03  167.965561  3451.341309  ...      3726756        925699
2022-01-04  167.900330  3471.280762  ...      3027262       2352482
2022-01-05  171.706848  3491.554443  ...      2436343       2076552
2022-01-06  172.185379  3506.247070  ...      2423850       2077754
2022-01-07  172.359406  3565.636963  ...      1475374       2107056
...                ...          ...  ...          ...           ...
2024-08-26  344.346069  5796.950195  ...       933372       1045317
2024-08-27  342.286774  5764.299805  ...      1231023        483025
2024-08-28  341.404205  5703.350098  ...      1768949        779730
2024-08-29  349.543396  5831.399902  ...      3205924       1062444
2024-08-30  350.720123  5855.250000  ...      3036374       2550399

Price                                                             \
Ticker     TATAMOTORS.NS TATASTEEL.NS   TCS.NS TECHM.NS TITAN.NS
Date
2022-01-03      32748423     38658030  2346158  1779147   921729
2022-01-04      24100985     59757310  2488606  2701533  1037293
2022-01-05      15420105     61861760  1733031  3138050  1244568
2022-01-06      16563230     53354000  1810293  4290750  1130508
2022-01-07      15532165     39738570  2460591  2103362  4625230
...                  ...          ...      ...      ...      ...
2024-08-26       9415039     32497603  1844164  1510157  1156681
2024-08-27       8813305     24523684   930697  1083351  1169007
2024-08-28       8145376     25195197  1848058  3033590   727481
2024-08-29      40658159     44452983  2133641  2194339   927472
2024-08-30      17647545     55134023  3637222  1926984  2116894

Price
Ticker     ULTRACEMCO.NS   UPL.NS  WIPRO.NS
Date
2022-01-03        250533  1157591   9280810
2022-01-04        315188  1247395  10228800
2022-01-05        400874  1156604  14711264
2022-01-06        403448  5436867  12883220
2022-01-07        543512  2052552  13120326
...                  ...      ...       ...
2024-08-26        234215  1283196  17351380
2024-08-27        184428  2705825   7965796
2024-08-28        201101  1369570  34375566
2024-08-29        406261  1530143  25685318
2024-08-30        462185  7616878  19434804

[656 rows x 245 columns]

In [5]:
data.isna().sum(axis=0).value_counts()

0    245
Name: count, dtype: int64

We see no NaN values, there was difficulty in downloading HDFC.NS data hence there's only 49 stocks here

In [6]:
returns = data['Close'].pct_change()
rolling_vol = returns.rolling(window=20).std()

Three Forecast Methods

In [7]:
def rolling_mean(rollig_vol,window=5): #method 1
    return rollig_vol.rolling(window).mean().dropna()
def ewma(returns:pd.Series,l=0.94): #method 2
    return (((returns**2).ewm(alpha=1-l).mean())**0.5).dropna()
def ar_1(rolling_vol:pd.Series): #method 3
    model = AutoReg(rolling_vol.dropna(), lags=1).fit() 
    return model.predict(start=len(data), end=len(data)) 

def normalise(arr:pd.Series):
    return (arr-arr.min())/(arr.max()-arr.min())

In [8]:
def compute_rmse(true, predicted):
    return np.sqrt(np.mean((true - predicted) ** 2))

def find_best_forecast(rolling_vol, returns):
    forecasts = {
        'Rolling Mean': rolling_mean(rolling_vol),
        'EWMA': ewma(returns),
        'AR(1)': ar_1(rolling_vol)
    }

    # Align forecast length to actual rolling vol for fair RMSE comparison
    aligned_vol = rolling_vol.dropna().iloc[-len(forecasts['Rolling Mean']):]
    rmses = {
        method: compute_rmse(aligned_vol, forecast.iloc[-len(aligned_vol):])
        for method, forecast in forecasts.items()
    }

    best_method = min(rmses, key=rmses.get)
    print(f"Best method: {best_method} with RMSE: {rmses[best_method]:.6f}")
    return forecasts[best_method]

In [9]:
def strat(df: pd.DataFrame):
    df = df.copy()
    df['ema14'] = df['Close'].ewm(span=14).mean()
    df['atr'] = (df['High'] - df['Low']).rolling(window=14).mean()

    df['signal'] = np.where((df['Close'] > df['ema14']) & (df['Close'].shift(1) <= df['ema14'].shift(1)), 1, 0)
    df['signal'] = np.where((df['Close'] < df['ema14']) & (df['Close'].shift(1) >= df['ema14'].shift(1)), -1, df['signal'])
    return df

# --- Backtesting for Multiple Assets ---
def backtest_multiple(data_dict, weights, signal_col='signal', initial_capital=1_000_000):
    capital_per_stock = {ticker: initial_capital * weight for ticker, weight in weights.items()}
    all_trades = {}
    all_daily = {}

    for ticker, df in data_dict.items():
        capital = capital_per_stock[ticker]
        df = df.copy()
        df['Signal'] = df[signal_col]
        position = 0
        cash = capital
        trades = []
        shares_held = 0
        entry_price = None
        atr = None
        stop_loss = None
        entry_date = None
        portfolio_value = []

        for date, row in df.iterrows():
            price = row['Close']
            signal = row['Signal']
            atr = row['atr']

            if position == 1 and price < stop_loss:
                signal = -1  # Trigger stop-loss exit

            if signal == 1 and position == 0:
                shares_to_buy = int(cash / price)
                invested = shares_to_buy * price
                cash -= invested
                shares_held = shares_to_buy
                entry_price = price
                entry_date = date
                stop_loss = price - 1.5 * atr
                position = 1

            elif signal == -1 and position == 1:
                pnl = (price - entry_price) * shares_held
                cash += shares_held * price
                trades.append({
                    'Entry Date': entry_date,
                    'Exit Date': date,
                    'Entry Price': entry_price,
                    'Exit Price': price,
                    'Shares': shares_held,
                    'PnL': pnl
                })
                shares_held = 0
                entry_price = None
                stop_loss = None
                position = 0
                entry_date = None

            current_value = cash + (shares_held * price if position == 1 else 0)
            portfolio_value.append({
                'Date': date,
                'Portfolio Value': current_value
            })

        all_trades[ticker] = pd.DataFrame(trades)
        all_daily[ticker] = pd.DataFrame(portfolio_value).set_index('Date')

    return all_trades, all_daily

def compute_metrics_all(trade_dict, daily_dict):
    all_metrics = {}

    for ticker in trade_dict:
        df = trade_dict[ticker]
        daily_df = daily_dict[ticker]
        if df.empty or daily_df.empty:
            continue

        r = daily_df['Portfolio Value'].iloc[-1] - daily_df['Portfolio Value'].iloc[0]
        rp = (r * 100) / daily_df['Portfolio Value'].iloc[0]

        sharpe = np.nan
        if 'Portfolio Value' in daily_df:
            returns = daily_df['Portfolio Value'].pct_change().dropna()
            if returns.std() != 0:
                sharpe = (returns.mean() / returns.std()) * np.sqrt(252)

        all_metrics[ticker] = {
            'Return': r,
            'Return %': rp,
            'Sharpe Ratio': sharpe,
            'Total Trades': len(df),
            'Winning Trades': (df['PnL'] > 0).sum(),
            'Losing Trades': (df['PnL'] <= 0).sum()
        }

    return pd.DataFrame(all_metrics).T

In [10]:
best_forecast_func = find_best_forecast(rolling_vol.mean(axis=1), returns.mean(axis=1))
risk_score = float(input("Enter risk averseness (0 = high risk appetite, 1 = risk averse): "))
normalized_vol = normalise(best_forecast_func)
latest_vol = rolling_vol.iloc[-1]  # latest vol per asset
distance = abs(normalise(latest_vol) - risk_score)
top3_tickers = distance.nsmallest(3).index.tolist()
print("Top 3 stocks matching risk profile:", top3_tickers)

c:\Users\Mani Prabha Singh\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\Mani Prabha Singh\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\Mani Prabha Singh\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\Mani Prabha Singh\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\tsa\deterministic.py:308: UserWarning: Only PeriodIndexes, DatetimeIndexes with a frequency set, RangesIndexes, and Index with a unit increment support extending. The index is set will contain the position relative to the data length.
  fcast_index = self._extend_index(index, steps, forecast_index)

Best method: Rolling Mean with RMSE: 0.000810
Top 3 stocks matching risk profile: ['HDFCLIFE.NS', 'ADANIPORTS.NS', 'TECHM.NS']

In [13]:
std_devs = data['Close'][top3_tickers].pct_change().std()
weights = 1 / std_devs
weights /= weights.sum()
weights_dict = weights.to_dict()
weights_dict

{'HDFCLIFE.NS': 0.37877753461489766,
 'ADANIPORTS.NS': 0.24881065703188182,
 'TECHM.NS': 0.3724118083532205}

In [18]:
df = data.xs("HDFCLIFE.NS", axis=1, level=1)
df

Price            Close        High         Low        Open   Volume
Date
2022-01-03  644.360718  648.471575  640.200344  647.827686  1892087
2022-01-04  646.985718  648.818234  642.924377  646.242796  2293391
2022-01-05  647.381958  652.037613  644.509364  648.818285  3326875
2022-01-06  640.794678  645.797004  638.813553  644.855958  2548339
2022-01-07  654.068176  656.693190  639.903150  640.893712  2168995
...                ...         ...         ...         ...      ...
2024-08-26  725.650024  734.000000  719.250000  734.000000  2131814
2024-08-27  739.549988  742.450012  719.299988  724.000000  5627130
2024-08-28  742.099976  746.549988  734.049988  739.950012  2995930
2024-08-29  736.900024  748.500000  731.849976  740.000000  3962913
2024-08-30  738.700012  742.700012  733.500000  736.900024  6227807

[656 rows x 5 columns]

In [27]:
data_dict = dict([(x,strat(data.xs(x,axis=1, level=1))) for x in top3_tickers])
trades,daily=backtest_multiple(data_dict,weights_dict)
metrics = compute_metrics_all(trades,daily)
display(metrics)

,Return,Return %,Sharpe Ratio,Total Trades,Winning Trades,Losing Trades
HDFCLIFE.NS,122192.342072,32.259659,0.720839,43.0,12.0,31.0
ADANIPORTS.NS,311462.415100,125.180496,1.231644,44.0,17.0,27.0
TECHM.NS,51683.048645,13.877930,0.368056,45.0,14.0,31.0